using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace MusicianInvoiceGenerator.Models
{
    public class GigModel
    {
        //GigModel represents a gig in code, it recieves/provides data from/to the database
        //id is null when the gig is generated by the program, and represents an Id from the Database when the database is used to generate the model
        public int? id;
        public string Details;
        public decimal Rate;

        public GigModel(string details, decimal rate)
        {
            Details = details;
            Rate = rate;
        }
        public GigModel(int id, string details, decimal rate)
        {
            this.id = id;
            this.Details = details;
            this.Rate = rate;
        }
    }
}