using MusicianInvoiceGenerator.Data;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace MusicianInvoiceGenerator.Models
{
    public class Invoice
    {
        //Invoice model class - a code representation of the invoice as would be stored in the database
        //Functions to ensure that a unique invoice number is generated, based on invoice date
        //This class is generated by the program to represent an invoice, it is NOT a representation of a database entry


        public int invoiceNo; //must be unique
        public ContactDetails SenderContact;
        public BankDetails SenderBankDetails;
        public ContactDetails RecipientContact;
        public List<GigModel> Gigs;

        public DateTime InvoiceDate;
        public DateTime DueDate;

        public bool Paid;

        public Invoice(ContactDetails senderContact, BankDetails senderBankDetails, ContactDetails recipientContact, List<GigModel> gigs,
            DateTime invoiceDate, DateTime dueDate)
        {
            SenderContact = senderContact;
            SenderBankDetails = senderBankDetails;
            RecipientContact = recipientContact;
            Gigs = gigs;
            InvoiceDate = invoiceDate;
            DueDate = dueDate;

            Paid = false;
            invoiceNo = InvoiceNumGenerator(invoiceDate);
        }
        /// <summary>
        /// This uses the date and a suffix number to uniquely identify the invoice in the database
        /// </summary>
        /// <param name="iDate">The send date of the invoice</param>
        /// <returns>a unique integer representing the invoice for the database identity column</returns>
        private protected int InvoiceNumGenerator(DateTime iDate)
        {
            string numGen = $"{iDate.ToString("yyyy")}{iDate.ToString("MM")}{iDate.ToString("dd")}0";
            int invoiceNo = Convert.ToInt32(numGen);
            while(!VerifyInvoiceNumber(invoiceNo))
            {
                invoiceNo++;
            }
            Debug.WriteLine(invoiceNo.ToString());
            return invoiceNo;
        }
        private bool VerifyInvoiceNumber(int i)
        {
            InvoiceDataAccess da = new InvoiceDataAccess();
            return da.InvoiceIdAvailable(i);
        }
    }
}